name: pro_juventudsaludable
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13 
  shimmer: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "icons/1.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
      # Presentación
      - assets/presentacion/FONDO.png
      # Pantalla Principal
      - assets/Plantel.png
      - assets/subsistema.png
      - assets/1.jpg
      - icons/1.png
      - icons/2.png
      - icons/3.png
      - icons/4.png
      # Slider Pantalla 1
      - assets/SliderPantalla1/image1.jpg
      - assets/SliderPantalla1/image3.jpg
      - assets/SliderPantalla1/image4.jpg
      - assets/SliderPantalla1/image5.jpg
      - assets/SliderPantalla1/image6.jpg
      - assets/SliderPantalla1/image7.jpg
      # Slider Pantalla 2
      - assets/SliderPantalla2/image1.jpg
      - assets/SliderPantalla2/image3.jpg
      - assets/SliderPantalla2/image4.jpg
      - assets/SliderPantalla2/image5.jpg
      - assets/SliderPantalla2/image7.jpg
      # Slider Pantalla 3
      - assets/SliderPantalla3/image1.jpg
      - assets/SliderPantalla3/image2.png
      - assets/SliderPantalla3/image3.jpg
      - assets/SliderPantalla3/image4.jpg
      - assets/SliderPantalla3/image5.jpg
      # Slider Pantalla 4
      - assets/SliderPantalla4/image1.png
      - assets/SliderPantalla4/image2.jpg
      - assets/SliderPantalla4/image3.jpg
      - assets/SliderPantalla4/image4.jpg
      - assets/SliderPantalla4/image5.jpg
      - assets/SliderPantalla4/image7.jpg
      # Slider Pantalla 5
      - assets/SliderPantalla5/image2.png
      - assets/SliderPantalla5/image3.jpg
      - assets/SliderPantalla5/image4.png
      - assets/SliderPantalla5/image5.jpg
      - assets/SliderPantalla5/image6.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #  - family: Trajan Pro
  #    fonts:
  #      - asset: assets/fonts/Pacifico-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #        weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
